import { LitElement, html } from "lit";
import { customElement } from "lit/decorators.js";
import init from "../../js/shared";
import { SyncMetaWidget } from "../../widget";

import "../../es6/debug_widget.js";
import { CONFIG, getWidgetTagName } from "../../es6/config";
// widget body used by all syncmeta widgets
@customElement(getWidgetTagName(CONFIG.WIDGET.NAME.DEBUG))
export class DebugWidget extends SyncMetaWidget(LitElement) {
  render() {
    return html`
      <link
        href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi"
        crossorigin="anonymous"
      />
      <style type="text/css">
        #debug-container {
          position: relative;
        }
      </style>
      <style type="text/css">
        @keyframes ldio-y0l1rz5jzvl {
          0% {
            opacity: 1;
          }
          100% {
            opacity: 0;
          }
        }
        .ldio-y0l1rz5jzvl div {
          /* somewhat wanted to center but too lazy to do it properly */
          left: 130px;
          top: 153px;
          position: absolute;
          animation: ldio-y0l1rz5jzvl linear 1s infinite;
          background: #00549f;
          width: 14px;
          height: 14px;
          border-radius: 7px / 7px;
          transform-origin: 7px 47px;
        }
        .ldio-y0l1rz5jzvl div:nth-child(1) {
          transform: rotate(0deg);
          animation-delay: -0.9166666666666666s;
          background: #00549f;
        }
        .ldio-y0l1rz5jzvl div:nth-child(2) {
          transform: rotate(30deg);
          animation-delay: -0.8333333333333334s;
          background: #00549f;
        }
        .ldio-y0l1rz5jzvl div:nth-child(3) {
          transform: rotate(60deg);
          animation-delay: -0.75s;
          background: #00549f;
        }
        .ldio-y0l1rz5jzvl div:nth-child(4) {
          transform: rotate(90deg);
          animation-delay: -0.6666666666666666s;
          background: #00549f;
        }
        .ldio-y0l1rz5jzvl div:nth-child(5) {
          transform: rotate(120deg);
          animation-delay: -0.5833333333333334s;
          background: #00549f;
        }
        .ldio-y0l1rz5jzvl div:nth-child(6) {
          transform: rotate(150deg);
          animation-delay: -0.5s;
          background: #00549f;
        }
        .ldio-y0l1rz5jzvl div:nth-child(7) {
          transform: rotate(180deg);
          animation-delay: -0.4166666666666667s;
          background: #00549f;
        }
        .ldio-y0l1rz5jzvl div:nth-child(8) {
          transform: rotate(210deg);
          animation-delay: -0.3333333333333333s;
          background: #00549f;
        }
        .ldio-y0l1rz5jzvl div:nth-child(9) {
          transform: rotate(240deg);
          animation-delay: -0.25s;
          background: #00549f;
        }
        .ldio-y0l1rz5jzvl div:nth-child(10) {
          transform: rotate(270deg);
          animation-delay: -0.16666666666666666s;
          background: #00549f;
        }
        .ldio-y0l1rz5jzvl div:nth-child(11) {
          transform: rotate(300deg);
          animation-delay: -0.08333333333333333s;
          background: #00549f;
        }
        .ldio-y0l1rz5jzvl div:nth-child(12) {
          transform: rotate(330deg);
          animation-delay: 0s;
          background: #00549f;
        }
        .loadingio-spinner-spinner-bl6ykl6ungk {
          width: 100%;
          height: 100%;
          display: inline-block;
          overflow: hidden;
          background: rgba(255, 255, 255, 0.5448185483870968);
        }
        .ldio-y0l1rz5jzvl {
          width: 100%;
          height: 100%;
          position: relative;
          transform: translateZ(0) scale(1);
          backface-visibility: hidden;
          transform-origin: 0 0; /* see note above */
        }
        .ldio-y0l1rz5jzvl div {
          box-sizing: content-box;
        }
        /* generated by https://loading.io/ */
      </style>
      <div id="debug-container">
        <div class="seperating_box">
          <h6>Select a JSON file</h6>
          <input
            type="file"
            id="file-object"
            accept=".json"
            value="Load a file"
          />
        </div>

        <hr />
        <div id="modelDiv" class="seperating_box">
          <h6>
            Import/Export/Delete a <strong>(Meta- or Guidance-)Model</strong>
          </h6>
          <button
            id="import-model"
            class="btn btn-secondary"
            title="Import a model to the canvas"
          >
            Import
          </button>
          <button
            id="export-model"
            class="btn btn-secondary"
            title="export the model as JSON"
          >
            Export
          </button>
          <button
            id="delete-model"
            title="delete the model"
            class="btn btn-danger"
          >
            Delete
          </button>
        </div>
        <hr />
        <div id="vlsDiv" class="seperating_box">
          <h6>
            Import/Export/Delete a <strong>Metamodel</strong> (Model Editor
            only)
          </h6>
          <button
            class="btn btn-secondary"
            id="import-meta-model"
            title="Refresh the role space to apply the new VLS."
          >
            Import
          </button>
          <button
            id="export-meta-model"
            title="Download the VLS as JSON"
            class="btn btn-secondary"
          >
            Export
          </button>
          <button
            id="delete-meta-model"
            title="Refresh the role space and delete the current modeling language"
            class="btn btn-danger"
          >
            Delete
          </button>
        </div>
        <hr />
        <div id="guidanceDiv" class="seperating_box">
          <h6>
            Import/Export/Delete a <strong>Logical Guidancemodel</strong> (Model
            Editor only)
          </h6>
          <button id="import-guidance-model" class="btn btn-secondary">
            Import
          </button>
          <button id="export-guidance-model" class="btn btn-secondary">
            Export
          </button>
          <button id="delete-guidance-model" class="btn btn-danger">
            Delete
          </button>
        </div>
        <hr />
        <div id="activityDiv" class="seperating_box">
          <h6>Export/Delete a <strong>Activity list</strong></h6>
          <button id="export-activity-list" class="btn btn-secondary">
            Export
          </button>
          <button id="delete-activity-list" class="btn btn-danger">
            Delete
          </button>
        </div>
      </div>
      <br />
    `;
  }

  connectedCallback() {
    super.connectedCallback();
    init();
  }

  disconnectedCallback() {
    super.disconnectedCallback();
  }
}
